export enum CoinActionTypes {
  REQUEST_GLOBAL_CRYPTO = '@@coin/REQUEST_GLOBAL_CRYPTO',
  FETCH_GLOBAL_CRYPTO = '@@coin/FETCH_GLOBAL_CRYPTO',
  FETCH_GLOBAL_CRYPTO_ERROR = '@@coin/FETCH_GLOBAL_CRYPTO_ERROR',
  REQUEST_ALL_COINS = '@@coin/REQUEST_ALL_COINS',
  FETCH_ALL_COINS = '@@coin/FETCH_ALL_COINS',
  FETCH_ALL_COINS_ERROR = '@@coin/FETCH_ALL_COINS_ERROR',
  REQUEST_SPECIFIC_COIN = '@@coin/REQUEST_SPECIFIC_COIN',
  FETCH_SPECIFIC_COIN = '@@coin/FETCH_SPECIFIC_COIN',
  FETCH_SPECIFIC_COIN_ERROR = '@@coin/FETCH_SPECIFIC_COIN_ERROR',
}

export enum MarketActionTypes {
  REQUEST_MARKET_FOR_COIN = '@@market/REQUEST_MARKET_FOR_COIN',
  FETCH_MARKET_FOR_COIN = '@@market/FETCH_MARKET_FOR_COIN',
  FETCH_MARKET_FOR_COIN_ERROR = '@@market/FETCH_MARKET_FOR_COIN_ERROR'
}

export enum ExchangeActionTypes {
  REQUEST_ALL_EXCHANGES = '@@exchange/REQUEST_ALL_EXCHANGES',
  FETCH_ALL_EXCHANGES = '@@exchange/FETCH_ALL_EXCHANGES',
  FETCH_ALL_EXCHANGES_ERROR = '@@exchange/FETCH_ALL_EXCHANGES_ERROR',
  REQUEST_EXCHANGE_FOR_COIN = '@@exchange/REQUEST_EXCHANGE_FOR_COIN',
  FETCH_EXCHANGE_FOR_COIN = '@@exchange/FETCH_EXCHANGE_FOR_COIN',
  FETCH_EXCHANGE_FOR_COIN_ERROR = '@@exchange/FETCH_EXCHANGE_FOR_COIN_ERROR'
}

export enum UIActionTypes {
  SET_IS_LOADING = '@@ui/SET_IS_LOADING',
}